### ISSUE TITLE
parse multiple files to analyze data for multiple days

### ISSUE THREAD

**Issue by jwickens** [madmaze/pyNmonAnalyzer#13]
This is a very important feature of the Java nmonvisualizer https://github.com/nmonvisualizer/nmonvisualizer , it seems like pyNmonAnalyzer is missing this. Create a new option to specify multiple files, call the parser iteratively, and join the data across days.

**Comment by heinrichvk** [comment]
Hello,

Axibase has a great product called ATSD which allows to parse and analyze multiple nmon files, data for multiple days and even stream nmon data as it is written to the file.

ATSD has built in visualization and forecasting features tailored for nmon data, allowing to immediately take advantage of your nmon data. Comes with 2 predefined portals for Linux and AIX systems.

There is a completely free version available for download.

You can learn more on the Axibase website: http://axibase.com/products/axibase-time-series-database/writing-data/nmon/

Regards,
Heinrich

**Comment by aldabrada** [comment]
> 

This has nothing to do with pyNmonAnalyzer

**Comment by aldabrada** [comment]
> 
Axibase has nothing to do with pyNmonAnalyzer
